jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - name: example page
        command: FORCE_COLOR=2 npx mocha spec.js --reporter spec | bin/term-to-html.js > mocha.html
      - store_artifacts:
          path: mocha.html
      - name: example dark page
        command: FORCE_COLOR=2 npx mocha spec.js --reporter spec | bin/term-to-html.js --theme dark > mocha-dark.html
      - store_artifacts:
          path: mocha-dark.html
      - run: npm run e2e
      - run: npm run semantic-release
orbs:
  node: circleci/node@1.1
version: 2.1
