jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: FORCE_COLOR=2 npx mocha spec.js --reporter spec | bin/term-to-html.js > mocha.html
      - store_artifacts:
          path: mocha.html
orbs:
  node: circleci/node@1.1
version: 2.1
